INSERT INTO USER("ID", "NAME") VALUES (1, 'USER1')
INSERT INTO USER("ID", "NAME") VALUES (2, 'USER2')
INSERT INTO USER("ID", "NAME") VALUES (3, 'USER3')
INSERT INTO USER("ID", "NAME") VALUES (4, 'USER4')

INSERT INTO ROLE("ID", "NAME") VALUES (1, 'USER_ROLE')
INSERT INTO ROLE("ID", "NAME") VALUES (2, 'USER_ADMIN')

INSERT INTO USER_ROLE("USER_ID", "ROLE_ID") VALUES (1, 1)
INSERT INTO USER_ROLE("USER_ID", "ROLE_ID") VALUES (2, 2)
