version: "3"
services:
  portalweb:
    image: portalweb:1.1
    ports:
      - "8080:8080"
    networks:
      - portaweb-mysql
    depends_on:
      - mysql-portal-db
 
  mysql-portal-db:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - portaweb-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=telecomunica
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  portaweb-mysql: